all: SFG_Spectra.exe SFG_Mu_Alpha.exe

SFG_Spectra.exe: SFG_Spectra.cpp 
	mpic++ -std=c++11 SFG_Spectra.cpp -o ../bin/SFG_Spectra.exe

SFG_Mu_Alpha.exe: SFG_Mu_Alpha.cpp 
	g++ -std=c++11 SFG_Mu_Alpha.cpp -o ../bin/SFG_Mu_Alpha.exe

